before_cache:
  - rm -fr $HOME/.m2/
cache:
  directories:
    - $HOME/.m2/

language: java
jdk:
  - oraclejdk8
before_deploy:
  - mvn javadoc:jar
  - export BIN=$(ls target/jrobotremoteserver-*-SNAPSHOT.jar)
  - export DOCS=$(ls target/jrobotremoteserver-*-SNAPSHOT-javadoc.jar)

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file:
    - "${BIN}"
    - "${DOCS}"
  skip_cleanup: true
  on:
    tags: true
